### ISSUE TITLE
Failed to run custom build command for `twiggy-opt v0.1.0`

### ISSUE THREAD

**Issue by yishn** [rustwasm/twiggy#53]
I'm trying to install twiggy with cargo, but on my Windows 10 I'll encounter the following build error:

~~~
error: failed to run custom build command for `twiggy-opt v0.1.0`
process didn't exit successfully: `C:\Users\D071863\AppData\Local\Temp\cargo-installUGK4Ht\release\build\twiggy-opt-8f09be37635e03b4\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=./definitions.js

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:945:5
stack backtrace:
   0: std::sys::windows::backtrace::unwind_backtrace
             at C:\projects\rust\src\libstd\sys\windows\backtrace\mod.rs:65
   1: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:71
   2: std::sys_common::backtrace::print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:59
   3: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:211
   4: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:227
   5: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:463
   6: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:350
   7: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:328
   8: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:71
   9: core::result::unwrap_failed
  10: core::result::unwrap_failed
  11: core::result::unwrap_failed
  12: <alloc::raw_vec::RawVec<T, A>>::reserve
  13: std::rt::lang_start_internal::{{closure}}
             at C:\projects\rust\src\libstd\rt.rs:59
  14: std::panicking::try::do_call<closure,i32>
             at C:\projects\rust\src\libstd\panicking.rs:310
  15: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:105
  16: std::panicking::try
             at C:\projects\rust\src\libstd\panicking.rs:289
  17: std::panic::catch_unwind
             at C:\projects\rust\src\libstd\panic.rs:374
  18: std::rt::lang_start_internal
             at C:\projects\rust\src\libstd\rt.rs:58
  19: main
  20: invoke_main
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:64
  21: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  22: BaseThreadInitThunk
  23: RtlUserThreadStart

warning: build failed, waiting for other jobs to finish...
error: failed to compile `twiggy v0.1.0`, intermediate artifacts can be found at `C:\Users\D071863\AppData\Local\Temp\cargo-installUGK4Ht`

Caused by:
  build failed
~~~

Any ideas of what's going on here?

**Comment by fitzgen** [comment]
It seems like maybe there are unix style path separators in the build script or something? But I had the impression that windows would do the Right Thing with them these days...

This is also purely speculation.

I will swap out the unwraps with expects, so we can get a better idea of which operation is failing, and then it would be really useful if you could try building again so we can pinpoint whats going on here.

**Comment by fitzgen** [comment]
D'oh, I know what this is.

I'm spawning `sh` in `build.rs` and that is probably not gonna work on windows...

**Comment by fitzgen** [comment]
@yishn can you verify that twiggy builds on windows on master now? Thanks!

**Comment by yishn** [comment]
Now twiggy builds fine on master! Thank you for the fast response!

**Comment by steveklabnik** [comment]
I am seeing this again

```shell
> cargo install twiggy
    Updating registry `https://github.com/rust-lang/crates.io-index`
  Installing twiggy v0.1.0
   Compiling unicode-xid v0.0.4
   Compiling glob v0.2.11
   Compiling quote v0.3.15
   Compiling unicode-xid v0.1.0
   Compiling winapi v0.3.5
   Compiling rustc-demangle v0.1.8
   Compiling unicode-width v0.1.5
   Compiling fixedbitset v0.1.9
   Compiling ordermap v0.3.5
   Compiling cfg-if v0.1.3
   Compiling byteorder v1.2.3
   Compiling strsim v0.7.0
   Compiling frozen v1.0.0
   Compiling bitflags v1.0.3
   Compiling vec_map v0.8.1
   Compiling twiggy-opt v0.1.0
   Compiling synom v0.11.3
   Compiling proc-macro2 v0.4.6
   Compiling textwrap v0.9.0
   Compiling cpp_demangle v0.2.9
   Compiling parity-wasm v0.28.0
   Compiling petgraph v0.4.12
   Compiling syn v0.11.11
error: failed to run custom build command for `twiggy-opt v0.1.0`
process didn't exit successfully: `C:\Users\steve\AppData\Local\Temp\cargo-installVoSWEy\release\build\twiggy-opt-828da1d72a0d293d\build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=./definitions.js

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', libcore\result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by steveklabnik** [comment]
Oh, apparently this just needs to be in a release; master does work.
